//
//  ThirdPageController.swift
//  Debug
//
//  Created by Betye on 6/26/18.
//  Copyright © 2018 JBZ Apps. All rights reserved.
//

import UIKit

class ThirdPageController: UIViewController {
    @IBOutlet weak var Button1: UIButton!
    @IBOutlet weak var Button2: UIButton!
    @IBOutlet weak var Button3: UIButton!
    @IBOutlet weak var textView: UITextView!
    
    var choice: Choice!
    override func viewDidLoad() {
        super.viewDidLoad()
        Button1.layer.cornerRadius = 15
        Button2.layer.cornerRadius = 15
        Button3.layer.cornerRadius = 15

        // Do any additional setup after loading the view.
      
        textView.text = choice.text
        Button1.setTitle(choice.buttons[0], for: .normal)
        Button2.setTitle(choice.buttons[1], for: .normal)
        Button3.setTitle(choice.buttons[2], for: .normal)
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
    var selectedChoice2 : Choice2!
    override func prepare(for segue: UIStoryboardSegue, sender: Any?){
        if segue.identifier == "Segue2"{
            let controller = segue.destination as! FourthPageController
            controller.choice2 = selectedChoice2
        }
    }
    @IBAction func Button1(_ sender:UIButton){
        if choice.title == "Abortion Law" {
            selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument.", textTwo: "Pro Life:\n•We tend to get emotionally wrapped up in what is a highly controversial topic. First, let’s establish the premise that the preborn are people. Since the preborn has human parents, she has to be human. And from the moment of conception, the being that begins as a single cell is biologically different from her mother.\n• Some will say that yes, it’s human. And yes, it’s alive, but it’s not a person. This is intellectually dishonest. We know from pure biology that from the very first moment of fertilization, the new being is neither the father nor the mother. She has her very own DNA, from the first moment of her creation.\n• The next premise is that it’s always wrong to kill innocent people. People who are born, most would say, deserve equal rights. Regardless of ability or disability, gender, religion, race, or socioeconomic status, our natural repulsion at violence and injustice shows us that this remains true: undue force upon innocent people is wrong. https://www.liveaction.org/news/why-abortion-is-wrong-the-pro-life-case/\n• Holding fast to pro-life convictions despite being mocked, ridiculed, and even physically assaulted is heroism.\n• Lastly, religion is a very impactful part of why people support pro-life. Last week, Richard Mourdock, the Tea Party-backed Republican Senate candidate in Indiana, declared during a debate that he was against abortion even in the event of rape because after much thought he “came to realize that life is that gift from God. And even when life begins in that horrible situation of rape, that it is something that God intended to happen.", image: #imageLiteral(resourceName: "Abortion") )
        } else if choice.title == "Climate Change" {
            selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: " Anti-Climate Change:\n•A large portion of republicans, more than 60% in fact, find that climate change is not a result of humans neglecting nature. This plays into how they view climate change as a whole, leading to them harboring negative feelings towards the subject.\n•Most say it is due to “natural changes in the environment” and should be treated as such.\n•“Being skeptical about global warming has become part of Republican or conservative identity,” said Riley E. Dunlap, a professor of environmental sociology at Oklahoma State University who was not involved in the study.\n• Republicans in the New York City area are about twice as likely to agree that human activities are driving global warming as their counterparts in Montana. But even in New York, barely 50 percent attribute the cause to humans.\n• This ties into President Trump disapproving of the Paris agreement, the action he took (which was to pull out) affected republicans and conservatives across the nation. That lead to the rise in doubtfulness regarding climate change.", image: #imageLiteral(resourceName: "Unknown") )
        } else if choice.title == "Gender" {
            selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: " Gender is a Social Construction:\n•People have a hard time believing that gender is a social construction because they have grown up with gender stereotypes and expectations in their culture.\n• It’s hard to believe that everyone, including yourself, is “doing gender.” However, we have been doing for so long that it’s hard to recognize it.\n• Economic wealth is a form of “performing/doing gender.”\n• Gender is one of the  main ways human organize their lives. Our society relies on a foreseeable division of jobs, goods, and government.\n•“Gender is so much the routine ground of everyday activities that questioning its taken-for-granted assumptions and presuppositions is like wondering about whether the sun will come up.” (“Night to his Day”:The Social Construction of Gender” by Judith Lorber)", image: #imageLiteral(resourceName: "Gender_neutral.svg") )
        } else if choice.title == "Microaggressions" {
            selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: "  Microaggression not an overreaction:\n•Microaggressions are people's subconscious racial biases acting out. They can be “verbal, nonverbal, and environmental slights, snubs, or insults, whether intentional or unintentional, which communicate hostile, derogatory, or negative messages” to another individual.\n• Microaggressions are suttle that they make the person feel they might be overreacting.\n• Examples of a racial microaggression: “A White man or woman clutches their purse or checks their wallet as a Black or Latino man approaches or passes them. (Hidden message: You and your group are criminals.)”.\n• Examples of a gender microaggression: An assertive female manager is labeled as a 'bitch,' while her male counterpart is described as 'a forceful leader.' (Hidden message: Women should be passive and allow men to be the decision makers.)", image: #imageLiteral(resourceName: "Race") )
        }
        performSegue(withIdentifier: "Segue2", sender : self)
    }
    
    @IBAction func Button2(_ sender:UIButton){
        if choice.title == "Abortion Law" {
            selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: "Learn more:\n•We tend to get emotionally wrapped up in what is a highly controversial topic. First, let’s establish the premise that the preborn are people. Since the preborn has human parents, she has to be human. And from the moment of conception, the being that begins as a single cell is biologically different from her mother.\n• Some will say that yes, it’s human. And yes, it’s alive, but it’s not a person. This is intellectually dishonest. We know from pure biology that from the very first moment of fertilization, the new being is neither the father nor the mother. She has her very own DNA, from the first moment of her creation.\n• The next premise is that it’s always wrong to kill innocent people. People who are born, most would say, deserve equal rights. Regardless of ability or disability, gender, religion, race, or socioeconomic status, our natural repulsion at violence and injustice shows us that this remains true: undue force upon innocent people is wrong. https://www.liveaction.org/news/why-abortion-is-wrong-the-pro-life-case/\n• Holding fast to pro-life convictions despite being mocked, ridiculed, and even physically assaulted is heroism.\n• Lastly, religion is a very impactful part of why people support pro-life. Last week, Richard Mourdock, the Tea Party-backed Republican Senate candidate in Indiana, declared during a debate that he was against abortion even in the event of rape because after much thought he “came to realize that life is that gift from God. And even when life begins in that horrible situation of rape, that it is something that God intended to happen.\n•Pro-choice don’t believe that women should have abortion, but believe that each women should have the right to choice.\n• Abortion ways heavily on any who has to decide. The decision process is an endless cycle of “what if’s.” It’s complicated and personal.\n•Abortions are not performed on someone who is over 12 weeks pregnant.\n• People who have decide to have abortions have not regret their choice. When they did have a baby they felt they were ready to be mothers.\n• When making a decision the mother has to think about whether they can afford to raise the child and if they can give the child a good life.", image: #imageLiteral(resourceName: "Abortion") )
        } else if choice.title == "Climate Change" {
            selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: "\n•Increase in the humidity in the air, and in a rise in sea level and temperature. These issues inform scientist the earth is warming.\n•There is an increase in wildfires and as temperatures the rises wildfire season is getting long in Western U.S.\n•Global warming is happening now and it is increased by the use of fossil fuels.\n•97 percent of Scientists agree that humans are the cause of global warming. A 2013 peer-reviewed study showed that  10,306 scientists, 97 percent of climate scientists, and over 97 percent of scientific articles,  argue that global warming is real and a large portion of it is due to humans\n•There is certainty on the effects of global warming, that the sea level is rising, and that  global warming is happening, but there is uncertainty what the future is going to be like.\n•A large portion of republicans, more than 60% in fact, find that climate change is not a result of humans neglecting nature. This plays into how they view climate change as a whole, leading to them harboring negative feelings towards the subject.\n•Most say it is due to “natural changes in the environment” and should be treated as such.\n•“Being skeptical about global warming has become part of Republican or conservative identity,” said Riley E. Dunlap, a professor of environmental sociology at Oklahoma State University who was not involved in the study.\n• Republicans in the New York City area are about twice as likely to agree that human activities are driving global warming as their counterparts in Montana. But even in New York, barely 50 percent attribute the cause to humans.\n• This ties into President Trump disapproving of the Paris agreement, the action he took (which was to pull out) affected republicans and conservatives across the nation. That lead to the rise in doubtfulness regarding climate change.", image: #imageLiteral(resourceName: "Unknown") )
        } else if choice.title == "Gender" {
            selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: "\n•People have a hard time believing that gender is a social construction because they have grown up with gender stereotypes and expectations in their culture.\n• It’s hard to believe that everyone, including yourself, is “doing gender.” However, we have been doing for so long that it’s hard to recognize it.\n• Economic wealth is a form of “performing/doing gender.”\n• Gender is one of the  main ways human organize their lives. Our society relies on a foreseeable division of jobs, goods, and government.\n•“Gender is so much the routine ground of everyday activities that questioning its taken-for-granted assumptions and presuppositions is like wondering about whether the sun will come up.n•The conservative position is that sex and gender are the same. Those who believe their gender is different from what their sex chromosomes and genitalia indicate are suffering from gender dysphoria and can recover with proper mental health treatment.\n•The conservative position is that bathroom use should be based upon sex because our genital differences are the reason we provide sex-differentiated privacy in the first place.\n•Conservatives believe that when they make the point that sex chromosomes play a role in gender identification Liberals ignore that point and say that sex and gender are not the same.", image: #imageLiteral(resourceName: "Gender_neutral.svg") )
        } else if choice.title == "Microaggressions" {
            selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: "\n• Conservatives have said that microaggressions is used as a buzzword that curtails free speech and promotes a liberal agenda of political correctness. They believe it has created a “victimhood” culture.\n•To conservatives, all this is petty and worse, stifling, and when supported by state university administrations, very much an imposition on free speech.\n• Conservatives feel muted because they can’t say things that have the potential of offending people, moreover this displays the sensitivity that they have seen grow in the past few years.\n• Some conservatives believe that microaggressions don’t exist, it is just a term to silence people who have differing opinions. A statement that can be found inflammatory when deemed a microaggression is “Where are you from” yet this is a fairly standard question to ask regardless of race, ethnicity, etc.\n•Microaggressions are people's subconscious racial biases acting out. They can be “verbal, nonverbal, and environmental slights, snubs, or insults, whether intentional or unintentional, which communicate hostile, derogatory, or negative messages” to another individual.\n• Microaggressions are suttle that they make the person feel they might be overreacting.\n• Examples of a racial microaggression: “A White man or woman clutches their purse or checks their wallet as a Black or Latino man approaches or passes them. (Hidden message: You and your group are criminals.)”.\n• Examples of a gender microaggression: An assertive female manager is labeled as a 'bitch,' while her male counterpart is described as 'a forceful leader.' (Hidden message: Women should be passive and allow men to be the decision makers.)", image: #imageLiteral(resourceName: "Race") )
        }
        performSegue(withIdentifier: "Segue2", sender : self)
    }
    @IBAction func Button3(_ sender:UIButton){
        if choice.title == "Abortion Law" {
        selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: "  Pro-choice:\n•Pro-choice don’t believe that women should have abortion, but believe that each women should have the right to choice.\n• Abortion ways heavily on any who has to decide. The decision process is an endless cycle of “what if’s.” It’s complicated and personal.\n•Abortions are not performed on someone who is over 12 weeks pregnant.\n• People who have decide to have abortions have not regret their choice. When they did have a baby they felt they were ready to be mothers.\n• When making a decision the mother has to think about whether they can afford to raise the child and if they can give the child a good life.", image: #imageLiteral(resourceName: "Abortion") )
    } else if choice.title == "Climate Change" {
            selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: "  Climate-change:\n•Increase in the humidity in the air, and in a rise in sea level and temperature. These issues inform scientist the earth is warming.\n•There is an increase in wildfires and as temperatures the rises wildfire season is getting long in Western U.S.\n•Global warming is happening now and it is increased by the use of fossil fuels.\n•97 percent of Scientists agree that humans are the cause of global warming. A 2013 peer-reviewed study showed that  10,306 scientists, 97 percent of climate scientists, and over 97 percent of scientific articles,  argue that global warming is real and a large portion of it is due to humans\n•There is certainty on the effects of global warming, that the sea level is rising, and that  global warming is happening, but there is uncertainty what the future is going to be like.", image: #imageLiteral(resourceName: "Unknown")  )
    } else if choice.title == "Gender" {
    selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: "  Gender is biological:\n•The conservative position is that sex and gender are the same. Those who believe their gender is different from what their sex chromosomes and genitalia indicate are suffering from gender dysphoria and can recover with proper mental health treatment.\n•The conservative position is that bathroom use should be based upon sex because our genital differences are the reason we provide sex-differentiated privacy in the first place.\n•Conservatives believe that when they make the point that sex chromosomes play a role in gender identification Liberals ignore that point and say that sex and gender are not the same.", image: #imageLiteral(resourceName: "Gender_neutral.svg") )
    } else if choice.title == "Microaggressions" {
    selectedChoice2 = Choice2(text: "Stay true to your belief. However, make sure you are aware of the othersides argument." ,textTwo: "   Microaggressions overreaction:\n• Conservatives have said that microaggressions is used as a buzzword that curtails free speech and promotes a liberal agenda of political correctness. They believe it has created a “victimhood” culture.\n•To conservatives, all this is petty and worse, stifling, and when supported by state university administrations, very much an imposition on free speech.\n• Conservatives feel muted because they can’t say things that have the potential of offending people, moreover this displays the sensitivity that they have seen grow in the past few years.\n• Some conservatives believe that microaggressions don’t exist, it is just a term to silence people who have differing opinions. A statement that can be found inflammatory when deemed a microaggression is “Where are you from” yet this is a fairly standard question to ask regardless of race, ethnicity, etc.", image: #imageLiteral(resourceName: "Race") )
    }
        performSegue(withIdentifier: "Segue2", sender : self)
    }

}
